# Generated by Django 2.1.1 on 2018-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anydocapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giatroi',
            name='amka',
            field=models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False),
        ),
    ]
