# Generated by Django 2.1.1 on 2018-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anydocapp', '0002_auto_20180925_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giatroi',
            name='description',
        ),
        migrations.AlterField(
            model_name='giatroi',
            name='radevous',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='radevous',
            field=models.TextField(max_length=3000),
        ),
    ]
